CREATE DATABASE CAR;
USE CAR;

SELECT * FROM CARSALES;

SELECT Make, Model,SalePrice FROM CARSALES;

SELECT * FROM CARSALES
WHERE CountryName = 'United Kingdom';

SELECT * FROM CARSALES
WHERE CountryName = 'United Kingdom' AND SalePrice>90000;

SELECT * FROM CARSALES
WHERE Make = 'Rolls Royce' OR Make = 'Aston Martin';

SELECT * FROM CARSALES
ORDER BY SalePrice DESC;

SELECT DISTINCT Make AS UNIQUE_MAKE FROM CARSALES;

SELECT * FROM CARSALES
WHERE Model LIKE 'Silver%';

SELECT * FROM CARSALES
WHERE Region='East Midlands' or 'Greater London Authority';

SELECT * FROM CARSALES
WHERE SalePrice  BETWEEN 80000 AND 100000;

SELECT * FROM CARSALES
WHERE IsDealer IS NULL;


SELECT * FROM CARSALES
WHERE TotalDiscount IS NOT NULL;

SELECT Make, Model, SalePrice - CostPrice AS PROFIT
FROM CARSALES;

SELECT MAKE, SUM(SalePrice) AS TOTAL_SALES FROM CARSALES
GROUP BY MAKE;

SELECT MAKE, AVG(SalePrice) AS AVG_SALES FROM CARSALES
GROUP BY MAKE;

SELECT MAKE, COUNT(Make) AS COUNT_MAKE FROM CARSALES
GROUP BY MAKE;

SELECT MAKE, AVG(SalePrice)>90000 AS AVG_SALES FROM CARSALES
GROUP BY MAKE;

-- OUT OF SYLLABUS
SELECT DISTINCT CountryName,Make, Model  FROM CARSALES;

SELECT Make, Model, COUNT(MAKE) FROM CARSALES
GROUP BY MAKE, MODEL;

-- OUT OF SYLLABUS
SELECT * FROM CARSALES
WHERE SalePrice>(Select AVG(SALEPRICE) FROM CARSALES );

-- INTERMEDIATE LEVEL
SELECT * FROM CARSALES
WHERE SalePrice > CostPrice;

SELECT * FROM CARSALES
WHERE CountryName = 'United Kingdom' AND SalePrice>80000;


SELECT * FROM CARSALES
WHERE Make= 'Rolls Royce' OR Color = 'Red';


SELECT * FROM CARSALES
ORDER BY CountryName AND SalePrice DESC;

SELECT distinct Color FROM CARSALES;

SELECT * FROM CARSALES
WHERE Make LIKE '%Royce%'; 

SELECT * FROM CARSALES
WHERE Make = 'Aston Martin' or 'Rolls Royce';

SELECT * FROM CARSALES
WHERE InvoiceDate between '2012-01-01' and '2012-12-31';

SELECT * FROM CARSALES
WHERE IsDealer IS NULL;

SELECT * FROM CARSALES
WHERE TotalDiscount IS NOT NULL;

SELECT Make, Model,  SalePrice + DeliveryCharge as TotalCost
FROM CARSALES;

SELECT * FROM CARSALES
ORDER BY SalePrice DESC;

SELECT * FROM CARSALES
WHERE Model LIKE '%Ghost';

SELECT * FROM CARSALES
WHERE LENGTH(REGION) >10;

SELECT * FROM CARSALES
WHERE SalePrice - CostPrice >10000 ;

SELECT * FROM CARSALES
WHERE CountryName != 'United Kingdom';

SELECT Make, Model, SalePrice - CostPrice AS PROFIT
FROM CARSALES;

SELECT * FROM CARSALES
WHERE InvoiceDate LIKE '2012-%';

SELECT * FROM CARSALES
WHERE CountryName = 'United Kingdom' AND (SalePrice > 80000 or Color =
'Red');


SELECT UPPER(Make), UPPER(Model) FROM CARSALES;


-- ADVANCE LEVEL QUESTION














