CREATE DATABASE SPORTS;
CREATE DATABASE IF NOT EXISTS SPORTS;
USE SPORTS;
DROP DATABASE SYS;


CREATE TABLE PLAYERS
( PLAYER_NAME VARCHAR(40),
PLAYER_ID INT);

CREATE TABLE TEAMS
( TEAM_ID INT, 
TEAM_NAME VARCHAR(40));

CREATE TABLE GAMES
( GAME_ID INT,
GAME_NAME VARCHAR(40),
HOME_TEAM_ID INT,
VENUE_ID INT);

CREATE TABLE COACHES
(COACH_ID INT,
COACH_NAME VARCHAR(40));

CREATE TABLE STADIUMS
(STADIUM_ID INT,
STADIUM_NAME VARCHAR(40),
LOCATION VARCHAR(40),
CAPACITY INT);

SHOW TABLES;

INSERT INTO STADIUMS
VALUES("23424","WANKHEDE STADIUM", "MUMBAI","33000");
SELECT * FROM STADIUMS;

INSERT INTO STADIUMS(STADIUM_ID,STADIUM_NAME)
VALUES(32447,"EDEN GARDENS");
SELECT * FROM STADIUMS;

INSERT INTO STADIUMS
VALUES("35532","AMBEDKAR STADIUM", "NEW DELHI","35000");
INSERT INTO STADIUMS
VALUES("45467","GREEN PARK STADIUM", "KANPUR","32000");
SELECT * FROM STADIUMS;

-- UPDATE MANIPULATES THE DATA 

UPDATE STADIUMS
SET STADIUM_ID ="90101"
WHERE STADIUM_ID="35532";

UPDATE STADIUMS 
SET LOCATION="KOLKATA", CAPACITY="68000"
WHERE STADIUM_ID="32447";

DESCRIBE STADIUMS_IN;

ALTER TABLE STADIUMS 
ADD ESTD_ INT; 

ALTER TABLE STADIUMS
MODIFY ESTD_ INT AFTER STADIUM_ID; 

ALTER TABLE STADIUMS  
RENAME TO STADIUMS_IN;

-- ALTER CHANGE THE DATA DEFINITION

ALTER TABLE STADIUMS_IN
MODIFY LOCATION VARCHAR(60);

ALTER TABLE STADIUMS_IN
RENAME COLUMN ESTD_ TO ESTD ;

DESCRIBE STADIUMS_IN;

SELECT * FROM STADIUMS_IN;

-- TO DELETE ALL RECORDS IN A TABLE
TRUNCATE TABLE STADIUMS_IN;

-- TO DELETE  PARTICULAR RECORD IN A TABLE OR ALL THE RECORDS-
DELETE FROM STADIUMS_IN
WHERE STADIUM_ID ="90101";

-- DROP IS USED TO REMOVE THE ENTIRE TABLE FROM DATABASE
DROP TABLE STADIUMS_IN;

INSERT INTO STADIUMS_IN (STADIUM_ID, ESTD, STADIUM_NAME, LOCATION, CAPACITY) VALUES
(4, 2017, 'Ekana International Cricket Stadium', 'Lucknow', 50000),
(5, 1987, 'M. Chinnaswamy Stadium', 'Bengaluru', 40000),
(6, 1969, 'Arun Jaitley Stadium', 'New Delhi', 41820);

-- Update Wankhede Stadium
UPDATE STADIUMS_IN
SET STADIUM_ID = 1 ,ESTD ="1974"
WHERE STADIUM_NAME = 'Wankhede Stadium';

-- Update Eden Gardens
UPDATE STADIUMS_IN
SET STADIUM_ID = 2 , ESTD = "1864"
WHERE STADIUM_NAME = 'Eden Gardens';

-- Update Green Park Stadium
UPDATE STADIUMS_IN
SET STADIUM_ID = 3,  ESTD = "1945"
WHERE STADIUM_NAME = 'Green Park Stadium';

SELECT * FROM STADIUMS_IN;



-- GRANT AND REVOKE

CREATE USER 'ARYAN'@'localhost' IDENTIFIED BY 'ABC';

GRANT ALL PRIVILEGES ON sports.* TO 'ARYAN'@'localhost';

SELECT CURRENT_USER();

REVOKE ALL PRIVILEGES ON sports.* FROM 'ARYAN'@'localhost';

SET autocommit = 0;
-- to see the status of autocommit.
SELECT @@autocommit;

INSERT INTO GAMES (GAME_ID, GAME_NAME, HOME_TEAM_ID, VENUE_ID) VALUES
(1, 'Soccer Match', 101, 1),
(2, 'Cricket Match', 102, 2),
(3, 'Basketball Game', 103, 3),
(4, 'Hockey Match', 104, 4),
(5, 'Tennis Match', 105, 5);

SELECT * FROM GAMES;

INSERT INTO GAMES (GAME_ID, GAME_NAME, HOME_TEAM_ID, VENUE_ID) 
VALUES(6, 'Football Match', 106, 10);

-- PERMANENT SAVING 
COMMIT;

SELECT * FROM GAMES;

-- NOT POSSIBLE TO ROLLBACK IF SAVED PERMANENTLY USING COMMIT. 
ROLLBACK;

COMMIT;

SELECT * FROM GAMES;

INSERT INTO GAMES (GAME_ID, GAME_NAME, HOME_TEAM_ID, VENUE_ID) 
VALUES(6, 'Football Match', 106, 10);





